# Generated by Django 3.1.6 on 2021-02-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dest',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
