# Generated by Django 3.1.6 on 2021-03-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('service', models.CharField(choices=[('HC', 'Haircut with clippers'), ('HCS', 'Haircut with clippers & scissors'), ('HBC', 'Haircut and beard combo'), ('B', 'Beard'), ('HE', 'Haircut & eyebrows'), ('DGH', 'Dying gray hair')], default='HC', max_length=200)),
                ('barber', models.CharField(choices=[('FA', 'First Available'), ('KA', 'Keith Apelon'), ('FS', 'Frank Swan'), ('DT', 'Dario Tequila')], default='FA', max_length=200)),
            ],
        ),
    ]
