# Generated by Django 3.1.6 on 2021-03-27 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210327_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
