# Generated by Django 3.1.6 on 2021-03-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20210327_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='barber',
            field=models.CharField(choices=[('First Available', 'First Available'), ('Keith Apelon', 'Keith Apelon'), ('Frank Swan', 'Frank Swan'), ('Dario Tequila', 'Dario Tequila')], max_length=200),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='service',
            field=models.CharField(choices=[('Haircut with clippers 10$', 'Haircut with clippers 10$'), ('Haircut with clippers & scissors 15$', 'Haircut with clippers & scissors 15$'), ('Haircut and beard combo 25$', 'Haircut and beard combo 25$'), ('Beard 5$', 'Beard 5$'), ('Haircut & eyebrows 15$', 'Haircut & eyebrows 15$'), ('Dying gray hair 25$', 'Dying gray hair 25$')], max_length=200),
        ),
    ]
